channels:
  - conda-forge
dependencies:
  # ---- core ----
  - python=3.11.11
  - ipython
  - bash
  - parallel
  - jq
  - nodejs=18.15.0
  - pyyaml
  - pip
  - pip:
      - setuptools>=68
      - wheel>=0.41
      - aws-parallelcluster==3.11.1
      - "botocore>=1.34.69,<1.35"
      - "boto3>=1.34.0,<1.35"
      - "s3transfer>=0.10.0,<0.11"
      - Flask==2.2.5
      - "Werkzeug<3.0"     # Flask 2.2 expects <3
