Region: us-west-2
Image:
  Name: dragen-el8-454-pc315-alma1-20260710
  RootVolume:
    Size: 100
Build:
  ParentImage: ami-044bef021cb86a54c
  InstanceType: f2.6xlarge
  Iam:
    AdditionalIamPolicies:
    - Policy: arn:aws:iam::108782052779:policy/dayec-pcluster-node-artifacts-read
  SubnetId: subnet-007038832fae23321
  SecurityGroupIds:
  - sg-0844dfdda1ec5a305
  UpdateOsPackages:
    Enabled: false
  Installation:
    LustreClient:
      Enabled: true
  Imds:
    ImdsSupport: v2.0
DevSettings:
  NodePackage: s3://lsmc-dayoa-references-usw2/runtime_assets/pcluster_backports/almalinux8/v3.15.0/fb900dd94b8bb1ca97334c499d4b7d27c5a9ebb6/aws-parallelcluster-node-3.15.0-56267ba9928832d5a1414753f99365574a6b89f3.tgz
  Cookbook:
    ChefCookbook: s3://lsmc-dayoa-references-usw2/runtime_assets/pcluster_backports/almalinux8/v3.15.0/fb900dd94b8bb1ca97334c499d4b7d27c5a9ebb6/aws-parallelcluster-cookbook-3.15.0-16a84e460c73222bde9076286c8b1574e391e6e6.tgz
  DisableKernelUpdate: true
  TerminateInstanceOnFailure: true
