ephemeral_cluster:
  config:
    ssh_key_name: [USESETVALUE, "daylily-omics-analysis-us-west-2", "daylily-omics-analysis-us-west-2"]
    s3_bucket_name: [USESETVALUE, "lsmc-dayoa-omics-analysis-us-west-2", "lsmc-dayoa-omics-analysis-us-west-2"]
    public_subnet_id: [USESETVALUE, "subnet-0e9acb65aba5a0330", "subnet-0e9acb65aba5a0330"]
    private_subnet_id: [USESETVALUE, "subnet-087a4872d0c34e642", "subnet-087a4872d0c34e642"]
    iam_policy_arn: [USESETVALUE, "arn:aws:iam::108782052779:policy/pclusterTagsAndBudget", "arn:aws:iam::108782052779:policy/pclusterTagsAndBudget"]
    cluster_name: [USESETVALUE, "tstVer4-1-1b", "tstVer4-1-1b"]
    budget_email: [USESETVALUE, "johnm@lsmc.com", "johnm@lsmc.com"]
    allowed_budget_users: [USESETVALUE, "ubuntu", "ubuntu"]
    budget_amount: [USESETVALUE, "200", "200"]
    global_allowed_budget_users: [USESETVALUE, "ubuntu", "ubuntu"]
    global_budget_amount: [USESETVALUE, "200", "200"]
    enforce_budget: [USESETVALUE, "skip", "skip"]
    cluster_template_yaml: [USESETVALUE, "config/day_cluster/prod_cluster.yaml", "config/day_cluster/prod_cluster.yaml"]
    headnode_instance_type: [USESETVALUE, "r7i.4xlarge", "r7i.4xlarge"]
    fsx_fs_size: [USESETVALUE, "12000", "12000"]
    enable_detailed_monitoring: [USESETVALUE, "false", "false"]
    delete_local_root: [USESETVALUE, "true", "true"]
    auto_delete_fsx: [USESETVALUE, "Delete", "Delete"]
    heartbeat_email: [USESETVALUE, "johnm@lsmc.com", "johnm@lsmc.com"]
    heartbeat_schedule: [USESETVALUE, "rate(60 minutes)", "rate(60 minutes)"]
    heartbeat_scheduler_role_arn: [USESETVALUE, "", ""]
    spot_instance_allocation_strategy: [USESETVALUE, "price-capacity-optimized", "price-capacity-optimized"]
    max_count_8I: [USESETVALUE, "1", "1"]
    max_count_128I: [USESETVALUE, "1", "1"]
    max_count_192I: [USESETVALUE, "1", "1"]
  template_defaults:
    headnode_instance_type: "r7i.4xlarge"
    fsx_fs_size: "12000"
    enable_detailed_monitoring: "false"
    delete_local_root: "true"
    auto_delete_fsx: "Delete"
    heartbeat_schedule: "rate(60 minutes)"
    spot_instance_allocation_strategy: "price-capacity-optimized"
    max_count_8I: "1"
    max_count_128I: "1"
    max_count_192I: "1"
