---
daylily:
  git_ephemeral_cluster_repo_tag: 16.1.43
  git_ephemeral_cluster_repo_release_tag: 16.1.43
  git_ephemeral_cluster_repo: https://github.com/lsmc-bio/daylily-ephemeral-cluster.git
  analysis_root: /fsx/analysis_results/
  sentieon_license:
    mode: server
    endpoint: license.sentieon.lsmc.bio:8990
  sentieon_tmpdir: /dev/shm/
  sentieon_install_dir: /fsx/references/runtime_assets/cached_envs/sentieon-genomics-202503.03/
