---
daylily:
  git_ephemeral_cluster_repo_tag: 10.0.94
  git_ephemeral_cluster_repo_release_tag: 10.0.94
  git_ephemeral_cluster_repo: https://github.com/lsmc-bio/daylily-ephemeral-cluster.git
  analysis_root: /fsx/analysis_results/
  sentieon_lic_path: /fsx/references/runtime_assets/cached_envs/Life_Sciences_Manufacturing_Corporation_eval.lic
  sentieon_tmpdir: /dev/shm/
  sentieon_install_dir: /fsx/references/runtime_assets/cached_envs/sentieon-genomics-202503.03/
