---
default_repository: daylily-omics-analysis
repositories:
  daylily-omics-analysis:
    display_name: "Daylily Omics Analysis"
    description: "Primary whole genome and multiomics workflows."
    https_url: https://github.com/Daylily-Informatics/daylily-omics-analysis.git
    ssh_url: git@github.com:Daylily-Informatics/daylily-omics-analysis.git
    default_ref: 0.7.356
    relative_path: daylily-omics-analysis
  rna-seq-star-deseq2:
    display_name: "RNA-seq STAR + DESeq2"
    description: "RNA sequencing alignment and differential expression analysis workflows."
    https_url: https://github.com/Daylily-Informatics/rna-seq-star-deseq2.git
    ssh_url: git@github.com:Daylily-Informatics/rna-seq-star-deseq2.git
    default_ref: main
    relative_path: rna-seq-star-deseq2
