ephemeral_cluster:
  config:
    reference_s3_uri: [USESETVALUE, "", "s3://lsmc-dayoa-references-usw2/"]
    control_data_s3_uri: [USESETVALUE, "", "s3://lsmc-dayoa-control-data-usw2/"]
    stage_s3_uri: [USESETVALUE, "", "s3://lsmc-ssf-sequencing-data/staged_external_data/"]
    export_destination_s3_uri: [USESETVALUE, "", "s3://lsmc-ssf-sequencing-data/derived/"]
    public_subnet_id: [USESETVALUE, "", "subnet-0e9acb65aba5a0330"]
    private_subnet_id: [USESETVALUE, "", "subnet-087a4872d0c34e642"]
    iam_policy_arn: [USESETVALUE, "", "arn:aws:iam::108782052779:policy/pclusterTagsAndBudget"]
    cluster_name: [USESETVALUE, "", "ifx-p2-250-0714"]
    budget_email: [USESETVALUE, "", "johnm@lsmc.com"]
    allowed_budget_users: [USESETVALUE, "", "ubuntu"]
    budget_amount: [USESETVALUE, "", "200"]
    global_allowed_budget_users: [USESETVALUE, "", "ubuntu"]
    global_budget_amount: [USESETVALUE, "", "600"]
    enforce_budget: [USESETVALUE, "", "true"]
    cluster_template_yaml: [USESETVALUE, "", "config/day_cluster/intel/us-west-2/us-west-2d/prod_cluster_intel_us-west-2d.yaml"]
    headnode_instance_type: [USESETVALUE, "", "r7i.2xlarge"]
    fsx_fs_size: [USESETVALUE, "", "4800"]
    fsx_deployment_type: [USESETVALUE, "", "PERSISTENT_2"]
    fsx_throughput_mbps_per_tib: [USESETVALUE, "", "250"]
    fsx_lustre_version: [USESETVALUE, "", "2.15"]
    fsx_metadata_mode: [USESETVALUE, "", "AUTOMATIC"]
    fsx_encryption_mode: [USESETVALUE, "", "AWS_MANAGED_FSX"]
    fsx_owner: [USESETVALUE, "", "DYEC"]
    fsx_lifecycle: [USESETVALUE, "", "CLUSTER_BOUND"]
    sweep_protection_tag: [USESETVALUE, "", "ursa-preserve=true"]
    enable_detailed_monitoring: [USESETVALUE, "", "false"]
    delete_local_root: [USESETVALUE, "", "true"]
    dyec_deploy_key_policy_arn: [USESETVALUE, "", "arn:aws:iam::108782052779:policy/DayECHeadnodeGitHubClone"]
    dyec_deploy_key_secret_arn: [USESETVALUE, "", "arn:aws:secretsmanager:us-west-2:108782052779:secret:dayec/github-deploy-keys/lsmc-bio/daylily-ephemeral-cluster-pE4FFN"]
    dayoa_deploy_key_policy_arn: [USESETVALUE, "", "arn:aws:iam::108782052779:policy/DayECHeadnodeGitHubClone"]
    dayoa_deploy_key_secret_arn: [USESETVALUE, "", "arn:aws:secretsmanager:us-west-2:108782052779:secret:dayec/github-deploy-keys/lsmc-bio-daylily-omics-analysis-igtfHD"]
    auto_delete_fsx: [USESETVALUE, "", "Delete"]
    heartbeat_email: [USESETVALUE, "", "johnm@lsmc.com"]
    heartbeat_schedule: [USESETVALUE, "", "rate(60 minutes)"]
    heartbeat_scheduler_role_arn: [USESETVALUE, "", "arn:aws:iam::108782052779:role/eventbridge-scheduler-to-sns"]
    spot_instance_allocation_strategy: [USESETVALUE, "", "price-capacity-optimized"]
    slurm_accounting_enabled: [USESETVALUE, "", "false"]
    slurm_accounting_create_db: [USESETVALUE, "", "false"]
    slurm_accounting_stack_name: [USESETVALUE, "", ""]
    slurm_accounting_database_name: [USESETVALUE, "", "dayec_slurm_acct"]
    slurm_accounting_db_username: [USESETVALUE, "", "slurm_acct"]
    slurm_accounting_instance_type: [USESETVALUE, "", "t4g.micro"]
    max_count_8I: [USESETVALUE, "", "1"]
    max_count_96I_NVME: [USESETVALUE, "", "1"]
    max_count_128I: [USESETVALUE, "", "1"]
    max_count_192I: [USESETVALUE, "", "1"]
    max_count_384I: [USESETVALUE, "", "1"]
    max_count_128I_C: [USESETVALUE, "", "1"]
    max_count_128I_M: [USESETVALUE, "", "1"]
    max_count_128I_R: [USESETVALUE, "", "1"]
    max_count_128I_NVME: [USESETVALUE, "", "1"]
    max_count_192I_C: [USESETVALUE, "", "1"]
    max_count_192I_M: [USESETVALUE, "", "1"]
    max_count_192I_R: [USESETVALUE, "", "1"]
    max_count_192I_NVME_C: [USESETVALUE, "", "1"]
    max_count_192I_NVME_M: [USESETVALUE, "", "1"]
    max_count_192I_NVME_R: [USESETVALUE, "", "1"]
    max_count_192I_HUGENVME: [USESETVALUE, "", "1"]
    max_count_384I_NVME_C: [USESETVALUE, "", "1"]
    max_count_384I_NVME_M: [USESETVALUE, "", "1"]
    max_count_384I_NVME_R: [USESETVALUE, "", "1"]
  template_defaults: {}
