---
daylily:
  git_tag: 0.7.220
  git_repo: https://github.com/RCRF/daylily-ephemeral-cluster.git
  git_repo_ssh: git@github.com:RCRF/daylily-ephemeral-cluster.git
  git_analysis_repo_tag: 0.7.220
  git_analysis_repo: https://github.com/RCRF/daylily-omics-analysis.git
  git_analysis_repo_ssh: git@github.com:RCRF/daylily-omics-analysis.git
  git_ephemeral_cluster_repo_tag: 0.7.220
  git_ephemeral_cluster_repo: https://github.com/RCRF/daylily-ephemeral-cluster.git
  git_ephemeral_cluster_repo_ssh: git@github.com:RCRF/daylily-ephemeral-cluster.git
  analysis_root: /fsx/analysis_results/
  daylily_image_cmd: "singularity pull --name /fsx/resources/environments/containers/daylily:0.7.196.simg docker://daylilyinformatics/daylily:0.7.196"
  daylily_image_path: /fsx/resources/environments/containers/daylily:0.7.196.simg
  sentieon_lic_path: /fsx/data/cached_envs/RCRF_Corporation_eval.lic
  sentieon_tmpdir: /dev/shm/
  sentieon_install_dir: /fsx/data/cached_envs/sentieon-genomics-202503.01.rc1/
