channels:
  - conda-forge
dependencies:
  - python==3.11.11
  - ipython
  - perl
  - yappi
  - bash                # >=4 for assoc arrays; conda bash satisfies it
  - yamllint
  - rclone
  - parallel
  - glances
  - fd-find
  - jq
  - yq
  - pip
  - pip:
      - aws-parallelcluster==3.13.2
      - boto3==1.40.35
      - botocore==1.40.35
      - daylily-omics-references @ git+https://github.com/Daylily-Informatics/daylily-omics-references.git@0.1.0
