Region: ${REGSUB_REGION}
Image:
  Os: almalinux8
  CustomAmi: ${REGSUB_DRAGEN_PCLUSTER_AMI}
HeadNode:
  InstanceType: ${REGSUB_HEADNODE_INSTANCE_TYPE}
  Image:
    CustomAmi: ${REGSUB_DRAGEN_PCLUSTER_AMI}
  Networking:
    ElasticIp: false
    SubnetId: ${REGSUB_PUB_SUBNET}
    # ${REGSUB_SLURM_ACCOUNTING_HEADNODE_NETWORKING}
  DisableSimultaneousMultithreading: false
  Dcv:
    Enabled: false
  LocalStorage:
    RootVolume:
      Size: 421
      VolumeType: gp3
      DeleteOnTermination: ${REGSUB_DELETE_LOCAL_ROOT}
    EphemeralVolume:
      MountDir: /head_root
  CustomActions:
    OnNodeStart:
      Script: ${REGSUB_S3_BUCKET_INIT}/install_slurm_job_submit_policy.sh
      Args:
      - ${REGSUB_REGION}
      - ${REGSUB_S3_BUCKET_INIT}
    OnNodeConfigured:
      Script: ${REGSUB_S3_BUCKET_INIT}/post_install_almalinux8_dragen.sh
      Args:
      - ${REGSUB_REGION}
      - ${REGSUB_S3_BUCKET_INIT}
      - ${REGSUB_SPOT_PRICE_WARN_THRESHOLD}
      - fsx
      - ${REGSUB_DRAGEN_LICENSE_SECRET_ARN}
      - headnode
  Iam:
    S3Access:
    - BucketName: ${REGSUB_S3_REFERENCE_BUCKET}
      EnableWriteAccess: false
    - BucketName: ${REGSUB_S3_CONTROL_DATA_BUCKET}
      EnableWriteAccess: false
    - BucketName: ${REGSUB_S3_STAGE_BUCKET}
      EnableWriteAccess: false
    - BucketName: ${REGSUB_S3_EXPORT_BUCKET}
      EnableWriteAccess: true
    AdditionalIamPolicies:
    - Policy: ${REGSUB_S3_IAM_POLICY}
    - Policy: ${REGSUB_DRAGEN_LICENSE_POLICY_ARN}
    - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    EnableMemoryBasedScheduling: false
    CustomSlurmSettings:
    - JobSubmitPlugins: lua
    - AccountingStoreFlags: job_comment
    - PrologFlags: Alloc
    ScaledownIdletime: 5
    Dns:
      DisableManagedDns: false
    QueueUpdateStrategy: DRAIN
    # ${REGSUB_SLURM_ACCOUNTING_DATABASE}
  SlurmQueues:
  - Name: dragen
    JobExclusiveAllocation: false
    CapacityType: SPOT
    AllocationStrategy: ${REGSUB_ALLOCATION_STRATEGY}
    ComputeSettings:
      LocalStorage:
        EphemeralVolume:
          MountDir: /scratch
    Image:
      CustomAmi: ${REGSUB_DRAGEN_PCLUSTER_AMI}
    ComputeResources:
    - Name: f26xlarge
      Instances:
      - InstanceType: f2.6xlarge
      MinCount: 0
      MaxCount: 1
      DynamicNodePriority: 100
      Networking:
        PlacementGroup:
          Enabled: false
      Efa:
        Enabled: false
    Networking:
      SubnetIds:
      - ${REGSUB_PRIVATE_SUBNET}
    CustomActions:
      OnNodeConfigured:
        Script: ${REGSUB_S3_BUCKET_INIT}/post_install_almalinux8_dragen.sh
        Args:
        - ${REGSUB_REGION}
        - ${REGSUB_S3_BUCKET_INIT}
        - ${REGSUB_SPOT_PRICE_WARN_THRESHOLD}
        - fsx
        - ${REGSUB_DRAGEN_LICENSE_SECRET_ARN}
        - dragen
    Iam:
      S3Access:
      - BucketName: ${REGSUB_S3_REFERENCE_BUCKET}
        EnableWriteAccess: false
      - BucketName: ${REGSUB_S3_CONTROL_DATA_BUCKET}
        EnableWriteAccess: false
      - BucketName: ${REGSUB_S3_STAGE_BUCKET}
        EnableWriteAccess: false
      - BucketName: ${REGSUB_S3_EXPORT_BUCKET}
        EnableWriteAccess: true
      AdditionalIamPolicies:
      - Policy: ${REGSUB_S3_IAM_POLICY}
      - Policy: ${REGSUB_DRAGEN_LICENSE_POLICY_ARN}
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  - Name: dragen-ondemand
    JobExclusiveAllocation: false
    CapacityType: ONDEMAND
    ComputeSettings:
      LocalStorage:
        EphemeralVolume:
          MountDir: /scratch
    Image:
      CustomAmi: ${REGSUB_DRAGEN_PCLUSTER_AMI}
    ComputeResources:
    - Name: f26xlargeod
      Instances:
      - InstanceType: f2.6xlarge
      MinCount: 0
      MaxCount: 1
      DynamicNodePriority: 100
      Networking:
        PlacementGroup:
          Enabled: false
      Efa:
        Enabled: false
    Networking:
      SubnetIds:
      - ${REGSUB_PRIVATE_SUBNET}
    CustomActions:
      OnNodeConfigured:
        Script: ${REGSUB_S3_BUCKET_INIT}/post_install_almalinux8_dragen.sh
        Args:
        - ${REGSUB_REGION}
        - ${REGSUB_S3_BUCKET_INIT}
        - ${REGSUB_SPOT_PRICE_WARN_THRESHOLD}
        - fsx
        - ${REGSUB_DRAGEN_LICENSE_SECRET_ARN}
        - dragen
    Iam:
      S3Access:
      - BucketName: ${REGSUB_S3_REFERENCE_BUCKET}
        EnableWriteAccess: false
      - BucketName: ${REGSUB_S3_CONTROL_DATA_BUCKET}
        EnableWriteAccess: false
      - BucketName: ${REGSUB_S3_STAGE_BUCKET}
        EnableWriteAccess: false
      - BucketName: ${REGSUB_S3_EXPORT_BUCKET}
        EnableWriteAccess: true
      AdditionalIamPolicies:
      - Policy: ${REGSUB_S3_IAM_POLICY}
      - Policy: ${REGSUB_DRAGEN_LICENSE_POLICY_ARN}
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  - Name: i192
    JobExclusiveAllocation: false
    CapacityType: SPOT
    AllocationStrategy: ${REGSUB_ALLOCATION_STRATEGY}
    Image:
      CustomAmi: ${REGSUB_DRAGEN_PCLUSTER_AMI}
    ComputeResources:
    - Name: mem192
      Instances:
      - InstanceType: m7i.48xlarge
      - InstanceType: r7i.48xlarge
      MinCount: 0
      MaxCount: ${REGSUB_MAX_COUNT_192I_M}
      SpotPrice: CALCULATE_MAX_SPOT_PRICE
      DynamicNodePriority: 200
      Networking:
        PlacementGroup:
          Enabled: false
      Efa:
        Enabled: false
    Networking:
      SubnetIds:
      - ${REGSUB_PRIVATE_SUBNET}
    CustomActions:
      OnNodeConfigured:
        Script: ${REGSUB_S3_BUCKET_INIT}/post_install_rhel8_dragen.sh
        Args:
        - ${REGSUB_REGION}
        - ${REGSUB_S3_BUCKET_INIT}
        - ${REGSUB_SPOT_PRICE_WARN_THRESHOLD}
        - fsx
        - cpu
    Iam:
      S3Access:
      - BucketName: ${REGSUB_S3_REFERENCE_BUCKET}
        EnableWriteAccess: false
      - BucketName: ${REGSUB_S3_CONTROL_DATA_BUCKET}
        EnableWriteAccess: false
      - BucketName: ${REGSUB_S3_STAGE_BUCKET}
        EnableWriteAccess: false
      - BucketName: ${REGSUB_S3_EXPORT_BUCKET}
        EnableWriteAccess: true
      AdditionalIamPolicies:
      - Policy: ${REGSUB_S3_IAM_POLICY}
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  - Name: i128shm
    JobExclusiveAllocation: false
    CapacityType: SPOT
    AllocationStrategy: ${REGSUB_ALLOCATION_STRATEGY}
    Image:
      CustomAmi: ${REGSUB_DRAGEN_PCLUSTER_AMI}
    ComputeResources:
    - Name: shm128
      Instances:
      - InstanceType: i4i.32xlarge
      - InstanceType: i4i.metal
      - InstanceType: m6a.32xlarge
      - InstanceType: m6i.32xlarge
      - InstanceType: m6i.metal
      - InstanceType: m6id.32xlarge
      - InstanceType: m6id.metal
      - InstanceType: m6idn.32xlarge
      - InstanceType: m6idn.metal
      - InstanceType: m6in.32xlarge
      - InstanceType: m6in.metal
      - InstanceType: m7a.32xlarge
      - InstanceType: m8i.32xlarge
      - InstanceType: m8ib.32xlarge
      - InstanceType: m8id.32xlarge
      - InstanceType: m8idb.32xlarge
      - InstanceType: m8idn.32xlarge
      - InstanceType: m8in.32xlarge
      - InstanceType: r6a.32xlarge
      - InstanceType: r6i.32xlarge
      - InstanceType: r6i.metal
      - InstanceType: r6id.32xlarge
      - InstanceType: r6id.metal
      - InstanceType: r6idn.32xlarge
      - InstanceType: r6idn.metal
      - InstanceType: r6in.32xlarge
      - InstanceType: r6in.metal
      - InstanceType: r7a.32xlarge
      - InstanceType: r7iz.32xlarge
      - InstanceType: r7iz.metal-32xl
      - InstanceType: r8i.32xlarge
      - InstanceType: r8ib.32xlarge
      - InstanceType: r8id.32xlarge
      - InstanceType: r8idb.32xlarge
      - InstanceType: r8idn.32xlarge
      - InstanceType: r8in.32xlarge
      - InstanceType: x1.32xlarge
      - InstanceType: x1e.32xlarge
      - InstanceType: x2idn.32xlarge
      - InstanceType: x2idn.metal
      - InstanceType: x2iedn.32xlarge
      - InstanceType: x2iedn.metal
      - InstanceType: x8i.32xlarge
      MinCount: 0
      MaxCount: ${REGSUB_MAX_COUNT_128I_M}
      SpotPrice: CALCULATE_MAX_SPOT_PRICE
      Networking:
        PlacementGroup:
          Enabled: false
      Efa:
        Enabled: false
    Networking:
      SubnetIds:
      - ${REGSUB_PRIVATE_SUBNET}
    CustomActions:
      OnNodeConfigured:
        Script: ${REGSUB_S3_BUCKET_INIT}/post_install_rhel8_dragen.sh
        Args:
        - ${REGSUB_REGION}
        - ${REGSUB_S3_BUCKET_INIT}
        - ${REGSUB_SPOT_PRICE_WARN_THRESHOLD}
        - fsx
        - cpu
    Iam:
      S3Access:
      - BucketName: ${REGSUB_S3_REFERENCE_BUCKET}
        EnableWriteAccess: false
      - BucketName: ${REGSUB_S3_CONTROL_DATA_BUCKET}
        EnableWriteAccess: false
      - BucketName: ${REGSUB_S3_STAGE_BUCKET}
        EnableWriteAccess: false
      - BucketName: ${REGSUB_S3_EXPORT_BUCKET}
        EnableWriteAccess: true
      AdditionalIamPolicies:
      - Policy: ${REGSUB_S3_IAM_POLICY}
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  - Name: i192shm
    JobExclusiveAllocation: false
    CapacityType: SPOT
    AllocationStrategy: ${REGSUB_ALLOCATION_STRATEGY}
    Image:
      CustomAmi: ${REGSUB_DRAGEN_PCLUSTER_AMI}
    ComputeResources:
    - Name: shm192
      Instances:
      - InstanceType: i7i.48xlarge
      - InstanceType: i7i.metal-48xl
      - InstanceType: i7ie.48xlarge
      - InstanceType: i7ie.metal-48xl
      - InstanceType: m6a.48xlarge
      - InstanceType: m6a.metal
      - InstanceType: m7a.48xlarge
      - InstanceType: m7a.metal-48xl
      - InstanceType: m7i.48xlarge
      - InstanceType: m7i.metal-48xl
      - InstanceType: m8a.48xlarge
      - InstanceType: m8a.metal-48xl
      - InstanceType: m8i.48xlarge
      - InstanceType: m8i.metal-48xl
      - InstanceType: m8ib.48xlarge
      - InstanceType: m8id.48xlarge
      - InstanceType: m8id.metal-48xl
      - InstanceType: m8idb.48xlarge
      - InstanceType: m8idn.48xlarge
      - InstanceType: m8in.48xlarge
      - InstanceType: r6a.48xlarge
      - InstanceType: r6a.metal
      - InstanceType: r7a.48xlarge
      - InstanceType: r7a.metal-48xl
      - InstanceType: r7i.48xlarge
      - InstanceType: r7i.metal-48xl
      - InstanceType: r8a.48xlarge
      - InstanceType: r8a.metal-48xl
      - InstanceType: r8i.48xlarge
      - InstanceType: r8i.metal-48xl
      - InstanceType: r8ib.48xlarge
      - InstanceType: r8id.48xlarge
      - InstanceType: r8id.metal-48xl
      - InstanceType: r8idb.48xlarge
      - InstanceType: r8idn.48xlarge
      - InstanceType: r8in.48xlarge
      - InstanceType: x8i.48xlarge
      - InstanceType: x8i.metal-48xl
      MinCount: 0
      MaxCount: ${REGSUB_MAX_COUNT_192I_M}
      SpotPrice: CALCULATE_MAX_SPOT_PRICE
      Networking:
        PlacementGroup:
          Enabled: false
      Efa:
        Enabled: false
    Networking:
      SubnetIds:
      - ${REGSUB_PRIVATE_SUBNET}
    CustomActions:
      OnNodeConfigured:
        Script: ${REGSUB_S3_BUCKET_INIT}/post_install_rhel8_dragen.sh
        Args:
        - ${REGSUB_REGION}
        - ${REGSUB_S3_BUCKET_INIT}
        - ${REGSUB_SPOT_PRICE_WARN_THRESHOLD}
        - fsx
        - cpu
    Iam:
      S3Access:
      - BucketName: ${REGSUB_S3_REFERENCE_BUCKET}
        EnableWriteAccess: false
      - BucketName: ${REGSUB_S3_CONTROL_DATA_BUCKET}
        EnableWriteAccess: false
      - BucketName: ${REGSUB_S3_STAGE_BUCKET}
        EnableWriteAccess: false
      - BucketName: ${REGSUB_S3_EXPORT_BUCKET}
        EnableWriteAccess: true
      AdditionalIamPolicies:
      - Policy: ${REGSUB_S3_IAM_POLICY}
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  - Name: i384shm
    JobExclusiveAllocation: false
    CapacityType: SPOT
    AllocationStrategy: ${REGSUB_ALLOCATION_STRATEGY}
    Image:
      CustomAmi: ${REGSUB_DRAGEN_PCLUSTER_AMI}
    ComputeResources:
    - Name: shm384
      Instances:
      - InstanceType: m8i.96xlarge
      - InstanceType: m8i.metal-96xl
      - InstanceType: m8ib.96xlarge
      - InstanceType: m8id.96xlarge
      - InstanceType: m8id.metal-96xl
      - InstanceType: m8idb.96xlarge
      - InstanceType: m8idn.96xlarge
      - InstanceType: m8in.96xlarge
      - InstanceType: r8i.96xlarge
      - InstanceType: r8i.metal-96xl
      - InstanceType: r8ib.96xlarge
      - InstanceType: r8id.96xlarge
      - InstanceType: r8id.metal-96xl
      - InstanceType: r8idb.96xlarge
      - InstanceType: r8idn.96xlarge
      - InstanceType: r8in.96xlarge
      - InstanceType: x8i.96xlarge
      - InstanceType: x8i.metal-96xl
      MinCount: 0
      MaxCount: ${REGSUB_MAX_COUNT_384I}
      SpotPrice: CALCULATE_MAX_SPOT_PRICE
      Networking:
        PlacementGroup:
          Enabled: false
      Efa:
        Enabled: false
    Networking:
      SubnetIds:
      - ${REGSUB_PRIVATE_SUBNET}
    CustomActions:
      OnNodeConfigured:
        Script: ${REGSUB_S3_BUCKET_INIT}/post_install_rhel8_dragen.sh
        Args:
        - ${REGSUB_REGION}
        - ${REGSUB_S3_BUCKET_INIT}
        - ${REGSUB_SPOT_PRICE_WARN_THRESHOLD}
        - fsx
        - cpu
    Iam:
      S3Access:
      - BucketName: ${REGSUB_S3_REFERENCE_BUCKET}
        EnableWriteAccess: false
      - BucketName: ${REGSUB_S3_CONTROL_DATA_BUCKET}
        EnableWriteAccess: false
      - BucketName: ${REGSUB_S3_STAGE_BUCKET}
        EnableWriteAccess: false
      - BucketName: ${REGSUB_S3_EXPORT_BUCKET}
        EnableWriteAccess: true
      AdditionalIamPolicies:
      - Policy: ${REGSUB_S3_IAM_POLICY}
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  - Name: i192nvme
    JobExclusiveAllocation: false
    CapacityType: SPOT
    AllocationStrategy: ${REGSUB_ALLOCATION_STRATEGY}
    ComputeSettings:
      LocalStorage:
        EphemeralVolume:
          MountDir: /scratch
    Image:
      CustomAmi: ${REGSUB_DRAGEN_PCLUSTER_AMI}
    ComputeResources:
    - Name: mem192nvme
      Instances:
      - InstanceType: i7i.48xlarge
      - InstanceType: i7ie.48xlarge
      MinCount: 0
      MaxCount: ${REGSUB_MAX_COUNT_192I_NVME_M}
      SpotPrice: CALCULATE_MAX_SPOT_PRICE
      DynamicNodePriority: 200
      Networking:
        PlacementGroup:
          Enabled: false
      Efa:
        Enabled: false
    Networking:
      SubnetIds:
      - ${REGSUB_PRIVATE_SUBNET}
    CustomActions:
      OnNodeConfigured:
        Script: ${REGSUB_S3_BUCKET_INIT}/post_install_rhel8_dragen.sh
        Args:
        - ${REGSUB_REGION}
        - ${REGSUB_S3_BUCKET_INIT}
        - ${REGSUB_SPOT_PRICE_WARN_THRESHOLD}
        - fsx
        - cpu
    Iam:
      S3Access:
      - BucketName: ${REGSUB_S3_REFERENCE_BUCKET}
        EnableWriteAccess: false
      - BucketName: ${REGSUB_S3_CONTROL_DATA_BUCKET}
        EnableWriteAccess: false
      - BucketName: ${REGSUB_S3_STAGE_BUCKET}
        EnableWriteAccess: false
      - BucketName: ${REGSUB_S3_EXPORT_BUCKET}
        EnableWriteAccess: true
      AdditionalIamPolicies:
      - Policy: ${REGSUB_S3_IAM_POLICY}
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
Monitoring:
  DetailedMonitoring: ${REGSUB_DETAILED_MONITORING}
  Logs:
    CloudWatch:
      Enabled: true
      RetentionInDays: 3
SharedStorage:
- MountDir: /fsx
  Name: fsx-${REGSUB_CLUSTER_NAME}
  StorageType: FsxLustre
  FsxLustreSettings:
    StorageCapacity: ${REGSUB_FSX_SIZE}
    DeploymentType: SCRATCH_2
    DeletionPolicy: ${REGSUB_SAVE_FSX}
    DataRepositoryAssociations:
    - Name: reference-data
      FileSystemPath: /references/
      DataRepositoryPath: ${REGSUB_S3_REFERENCE_URI}/
      BatchImportMetaDataOnCreate: true
      AutoImportPolicy:
      - NEW
      - CHANGED
      - DELETED
Tags:
- Key: aws-parallelcluster-username
  Value: "${REGSUB_USERNAME}"
- Key: aws-parallelcluster-jobid
  Value: "${REGSUB_AWS_ACCOUNT_ID}"
- Key: aws-parallelcluster-project
  Value: "${REGSUB_PROJECT}"
- Key: aws-parallelcluster-clustername
  Value: "${REGSUB_CLUSTER_NAME}"
- Key: aws-parallelcluster-enforce-budget
  Value: ${REGSUB_ENFORCE_BUDGET}
- Key: aws-parallelcluster-cost-center-region
  Value: "${REGSUB_COST_CENTER_REGION}"
- Key: aws-parallelcluster-cost-center-table
  Value: "${REGSUB_COST_CENTER_TABLE}"
- Key: aws-parallelcluster-cost-center-usage-table
  Value: "${REGSUB_COST_CENTER_USAGE_TABLE}"
- Key: aws-parallelcluster-daylily-git-deets
  Value: "${REGSUB_DAYLILY_GIT_DEETS}"
- Key: aws-parallelcluster-monitor-bucket
  Value: "${REGSUB_S3_BUCKET_INIT}"
DevSettings:
  Cookbook:
    ChefCookbook: ${REGSUB_PCLUSTER_COOKBOOK_URI}
  Timeouts:
    HeadNodeBootstrapTimeout: 7200
    ComputeNodeBootstrapTimeout: 7200
