name: Render README version
on:
  push:
    tags:
      - 'v*'
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Compute version
        run: echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Render
        run: |
          sed "s/{{VERSION}}/${VERSION}/g" README.tmpl.md > README.md
      - name: Commit README
        run: |
          if ! git diff --quiet -- README.md; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "docs: update README version to ${VERSION}"
            git push
          fi
